import { Etablissement, Utilisateur, Produit, MouvementStock } from '@/types';

export const SEED_ETABLISSEMENT: Etablissement = {
  id: 'etab-capitole-douala',
  nom: 'LE CAPITOLE BAR & LOUNGE',
  type: 'snack_bar',
  ville: 'Douala',
  adresse: 'Akwa - Boulevard de la Liberté',
  plan: 'Premium',
  statut_abonnement: 'essai',
  date_fin_essai: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
  date_prochain_paiement: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
  created_at: new Date().toISOString(),
};

export const SEED_UTILISATEURS: Utilisateur[] = [
  {
    id: 'user-patron',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Madame TAKAM (Patronne)',
    role: 'Patron',
    pin_code: '1234', // PIN 4 chiffres
    telephone: '699001122',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-gerant',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Jean-Paul KENGNE (Gérant)',
    role: 'Gérant',
    pin_code: '5678', // PIN 4 chiffres
    telephone: '675443322',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-employe',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Chantal MBALLA (Serveuse)',
    role: 'Employé',
    pin_code: '0000', // PIN 4 chiffres
    telephone: '655889900',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
];

export const SEED_PRODUITS: Produit[] = [
  {
    id: 'prod-beaufort',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Beaufort Lager',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 12,
    bouteilles_vrac: 5,
    bouteilles_par_casier: 24,
    quantite_totale_bouteilles: 293, // 12 * 24 + 5
    seuil_alerte: 50, // Moins de ~2 casiers = alerte
    prix_achat_casier: 6500,
    prix_vente_bouteille: 650,
    actif: true,
  },
  {
    id: 'prod-33export',
    etablissement_id: 'etab-capitole-douala',
    nom: '33 Export',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 8,
    bouteilles_vrac: 12,
    bouteilles_par_casier: 24,
    quantite_totale_bouteilles: 204,
    seuil_alerte: 48,
    prix_achat_casier: 6000,
    prix_vente_bouteille: 600,
    actif: true,
  },
  {
    id: 'prod-guinness',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Guinness Foreign Extra',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 1, // ALERTE STOCK BAS
    bouteilles_vrac: 3,
    bouteilles_par_casier: 24,
    quantite_totale_bouteilles: 27,
    seuil_alerte: 48, // Seuil à 48 -> Déclenche alerte stock bas !
    prix_achat_casier: 11000,
    prix_vente_bouteille: 1000,
    actif: true,
  },
  {
    id: 'prod-castel',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Castel Beer',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 5,
    bouteilles_vrac: 8,
    bouteilles_par_casier: 24,
    quantite_totale_bouteilles: 128,
    seuil_alerte: 48,
    prix_achat_casier: 6500,
    prix_vente_bouteille: 650,
    actif: true,
  },
  {
    id: 'prod-mutzig',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Mützig',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 6,
    bouteilles_vrac: 2,
    bouteilles_par_casier: 24,
    quantite_totale_bouteilles: 146,
    seuil_alerte: 48,
    prix_achat_casier: 6800,
    prix_vente_bouteille: 700,
    actif: true,
  },
  {
    id: 'prod-pouletdg',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Poulet DG Capitole',
    categorie: 'Plat Chaud',
    unite: 'bouteille',
    casiers_pleins: 0,
    bouteilles_vrac: 15,
    bouteilles_par_casier: 12,
    quantite_totale_bouteilles: 15,
    seuil_alerte: 5,
    prix_achat_casier: 3500,
    prix_vente_bouteille: 5000,
    actif: true,
  },
];

export const SEED_MOUVEMENTS: MouvementStock[] = [
  {
    id: 'mvt-1',
    etablissement_id: 'etab-capitole-douala',
    produit_id: 'prod-beaufort',
    type_mouvement: 'entree',
    quantite_bouteilles: 120, // 5 casiers
    utilisateur_id: 'user-gerant',
    note_motif: 'Reconstitution du stock fournisseur Brasseries',
    sync_status: 'synced',
    client_timestamp: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    created_at: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
  },
  {
    id: 'mvt-2',
    etablissement_id: 'etab-capitole-douala',
    produit_id: 'prod-guinness',
    type_mouvement: 'sortie',
    quantite_bouteilles: 12,
    utilisateur_id: 'user-employe',
    note_motif: 'Vente table VIP 1',
    sync_status: 'synced',
    client_timestamp: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
    created_at: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
  },
  {
    id: 'mvt-3',
    etablissement_id: 'etab-capitole-douala',
    produit_id: 'prod-guinness',
    type_mouvement: 'casse_perte',
    quantite_bouteilles: 2,
    utilisateur_id: 'user-employe',
    note_motif: 'Bouteilles cassées au service par la serveuse',
    sync_status: 'synced',
    client_timestamp: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    created_at: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
];
