import {
  Etablissement,
  Utilisateur,
  Produit,
  MouvementStock,
  Client,
  Facture,
  RemboursementCredit,
  ChargeJournaliere,
  TransactionVente,
  CommandeEnLigne,
  Caisse,
  TARIFS_ABONNEMENT,
} from '@/types';

const NOW = Date.now();
const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;

export const SEED_ETABLISSEMENT: Etablissement = {
  id: 'etab-capitole-douala',
  nom: 'LE CAPITOLE SNACK-BAR',
  type: 'snack_bar',
  type_activite: 'snack',
  ville: 'Douala',
  adresse: 'Akwa - Boulevard de la Liberté',
  plan: 'Premium',
  statut_abonnement: 'essai',
  tarif_mensuel: TARIFS_ABONNEMENT.snack, // 10,000 FCFA
  date_fin_essai: new Date(NOW + SEVEN_DAYS_MS).toISOString(),
  date_prochain_paiement: new Date(NOW + SEVEN_DAYS_MS).toISOString(),
  created_at: new Date().toISOString(),
};

export const SEED_ETABLISSEMENTS_LIST: Etablissement[] = [
  SEED_ETABLISSEMENT,
  {
    id: 'etab-citadelle-douala',
    nom: 'BAR LA CITADELLE',
    type: 'bar',
    type_activite: 'bar',
    ville: 'Douala',
    adresse: 'Akwa Nord',
    plan: 'Basique',
    statut_abonnement: 'essai',
    tarif_mensuel: TARIFS_ABONNEMENT.bar, // 5,000 FCFA
    date_fin_essai: new Date(NOW + SEVEN_DAYS_MS).toISOString(),
    date_prochain_paiement: new Date(NOW + SEVEN_DAYS_MS).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'etab-elegance-akwa',
    nom: 'BOUTIQUE ÉLÉGANCE AKWA',
    type: 'boutique',
    type_activite: 'boutique',
    ville: 'Douala',
    adresse: 'Rue Joffre - Akwa',
    plan: 'Premium',
    statut_abonnement: 'essai',
    tarif_mensuel: TARIFS_ABONNEMENT.boutique, // 5,000 FCFA
    date_fin_essai: new Date(NOW + SEVEN_DAYS_MS).toISOString(),
    date_prochain_paiement: new Date(NOW + SEVEN_DAYS_MS).toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const SEED_UTILISATEURS: Utilisateur[] = [
  // --- SNACK RÔLES (Patron, Directeur, Caissière, Serveuse) ---
  {
    id: 'user-patron-snack',
    etablissement_id: 'etab-capitole-douala',
    nom: 'M. TAKAM (Patron à distance)',
    role: 'Patron',
    pin_code: '1234',
    telephone: '699001122',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-directeur-snack',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Mme TAKAM (Directrice)',
    role: 'Directeur',
    pin_code: '9999',
    telephone: '677112233',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-caissiere-1',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Marie (Caissière Principal)',
    role: 'Caissière',
    pin_code: '5678',
    telephone: '675443322',
    caisse_id: 'caisse-1',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-serveuse-1',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Chantal (Serveuse)',
    role: 'Serveuse',
    pin_code: '0000',
    telephone: '655889900',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },

  // --- BOUTIQUE RÔLES (Patronne, Employé) ---
  {
    id: 'user-patron-elegance',
    etablissement_id: 'etab-elegance-akwa',
    nom: 'Mme EBOLE (Patronne)',
    role: 'Patronne',
    pin_code: '1234',
    telephone: '699334455',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-employe-boutique',
    etablissement_id: 'etab-elegance-akwa',
    nom: 'Vanessa (Vendeuse / Employée)',
    role: 'Employé',
    pin_code: '1111',
    telephone: '677112233',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },

  // --- BAR RÔLES (Patronne, Serveuse) ---
  {
    id: 'user-patron-bar',
    etablissement_id: 'etab-citadelle-douala',
    nom: 'Tante ROSE (Patronne Bar)',
    role: 'Patronne',
    pin_code: '1234',
    telephone: '699887766',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
  {
    id: 'user-serveuse-bar',
    etablissement_id: 'etab-citadelle-douala',
    nom: 'Clarisse (Serveuse)',
    role: 'Serveuse',
    pin_code: '2222',
    telephone: '655112244',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    actif: true,
  },
];

export const SEED_CAISSES: Caisse[] = [
  {
    id: 'caisse-1',
    etablissement_id: 'etab-capitole-douala',
    caissiere_id: 'user-caissiere-1',
    caissiere_nom: 'Marie (Caissière Principal)',
    nom_caisse: 'Caisse Principale Comptoir',
    total_encaisse_du_jour: 145000,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'caisse-2',
    etablissement_id: 'etab-capitole-douala',
    caissiere_id: 'user-caissiere-1',
    caissiere_nom: 'Marie',
    nom_caisse: 'Caisse Carré VIP',
    total_encaisse_du_jour: 85000,
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const SEED_PRODUITS: Produit[] = [
  // --- PRODUITS BAR & SNACK ---
  {
    id: 'prod-beaufort',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Beaufort Lager 65cl',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 12,
    bouteilles_vrac: 5,
    bouteilles_par_casier: 24,
    quantite_totale: 293,
    seuil_alerte: 50,
    prix_achat_casier: 6500,
    prix_vente_bouteille: 650,
    prix_achat_unitaire: 271,
    prix_vente_unitaire: 650,
    cout_achat_unitaire_cmp: 271,
    actif: true,
  },
  {
    id: 'prod-33export',
    etablissement_id: 'etab-capitole-douala',
    nom: '33 Export 65cl',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 8,
    bouteilles_vrac: 12,
    bouteilles_par_casier: 24,
    quantite_totale: 204,
    seuil_alerte: 48,
    prix_achat_casier: 6000,
    prix_vente_bouteille: 600,
    prix_achat_unitaire: 250,
    prix_vente_unitaire: 600,
    cout_achat_unitaire_cmp: 250,
    actif: true,
  },
  {
    id: 'prod-guinness',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Guinness Foreign Extra',
    categorie: 'Bière',
    unite: 'bouteille',
    casiers_pleins: 1,
    bouteilles_vrac: 3,
    bouteilles_par_casier: 24,
    quantite_totale: 27,
    seuil_alerte: 48,
    prix_achat_casier: 11000,
    prix_vente_bouteille: 1000,
    prix_achat_unitaire: 458,
    prix_vente_unitaire: 1000,
    cout_achat_unitaire_cmp: 458,
    actif: true,
  },

  // --- PRODUITS BOUTIQUE DE VÊTEMENTS (VARIANTES TAILLE/COULEUR) ---
  {
    id: 'prod-robe-soie',
    etablissement_id: 'etab-elegance-akwa',
    nom: 'Robe de Soirée Éléganza',
    categorie: 'Robe / Femme',
    unite: 'piece',
    quantite_totale: 18,
    seuil_alerte: 5,
    prix_achat_unitaire: 12000,
    prix_vente_unitaire: 25000,
    cout_achat_unitaire_cmp: 12000,
    variantes: [
      { id: 'var-robe-s-rouge', produit_id: 'prod-robe-soie', sku_code: 'ROBE-RED-S', taille: 'S', couleur: 'Rouge', quantite_stock: 4 },
      { id: 'var-robe-m-noir', produit_id: 'prod-robe-soie', sku_code: 'ROBE-BLK-M', taille: 'M', couleur: 'Noir', quantite_stock: 8 },
      { id: 'var-robe-l-bleu', produit_id: 'prod-robe-soie', sku_code: 'ROBE-BLU-L', taille: 'L', couleur: 'Bleu Roi', quantite_stock: 6 },
    ],
    actif: true,
  },
  {
    id: 'prod-chemise-homme',
    etablissement_id: 'etab-elegance-akwa',
    nom: 'Chemise Slim Fit Coton',
    categorie: 'Chemise / Homme',
    unite: 'piece',
    quantite_totale: 25,
    seuil_alerte: 8,
    prix_achat_unitaire: 7000,
    prix_vente_unitaire: 15000,
    cout_achat_unitaire_cmp: 7000,
    variantes: [
      { id: 'var-chem-m-blanc', produit_id: 'prod-chemise-homme', sku_code: 'CHEM-WHT-M', taille: 'M', couleur: 'Blanc pure', quantite_stock: 10 },
      { id: 'var-chem-l-bleuciel', produit_id: 'prod-chemise-homme', sku_code: 'CHEM-SKB-L', taille: 'L', couleur: 'Bleu Ciel', quantite_stock: 9 },
      { id: 'var-chem-xl-blanc', produit_id: 'prod-chemise-homme', sku_code: 'CHEM-WHT-XL', taille: 'XL', couleur: 'Blanc pure', quantite_stock: 6 },
    ],
    actif: true,
  },
  {
    id: 'prod-chaussure-cuir',
    etablissement_id: 'etab-elegance-akwa',
    nom: 'Chaussure Richelieu Cuir',
    categorie: 'Chaussures',
    unite: 'piece',
    quantite_totale: 12,
    seuil_alerte: 4,
    prix_achat_unitaire: 22000,
    prix_vente_unitaire: 45000,
    cout_achat_unitaire_cmp: 22000,
    variantes: [
      { id: 'var-chass-41-marron', produit_id: 'prod-chaussure-cuir', sku_code: 'RIC-BRN-41', taille: '41', couleur: 'Marron Glacé', quantite_stock: 3 },
      { id: 'var-chass-42-noir', produit_id: 'prod-chaussure-cuir', sku_code: 'RIC-BLK-42', taille: '42', couleur: 'Noir Ébène', quantite_stock: 5 },
      { id: 'var-chass-43-noir', produit_id: 'prod-chaussure-cuir', sku_code: 'RIC-BLK-43', taille: '43', couleur: 'Noir Ébène', quantite_stock: 4 },
    ],
    actif: true,
  },
];

export const SEED_COMMANDES_LIGNE: CommandeEnLigne[] = [
  {
    id: 'cmd-001',
    etablissement_id: 'etab-elegance-akwa',
    numero_commande: 'CMD-2026-001',
    client_nom: 'Mme CHANTAL VIP',
    client_telephone: '237699445566',
    adresse_livraison: 'Douala - Bonapriso (Face Clinique)',
    statut: 'en_livraison',
    lignes: [
      {
        produit_id: 'prod-robe-soie',
        variante_id: 'var-robe-m-noir',
        nom_produit: 'Robe de Soirée Éléganza',
        detail_variante: 'Taille M / Noir',
        quantite: 1,
        prix_unitaire: 25000,
      },
    ],
    montant_total: 25000,
    created_at: new Date(NOW - 3600 * 1000 * 3).toISOString(),
  },
];

export const SEED_MOUVEMENTS: MouvementStock[] = [
  {
    id: 'mvt-1',
    etablissement_id: 'etab-capitole-douala',
    produit_id: 'prod-beaufort',
    type_mouvement: 'entree',
    quantite_bouteilles: 120,
    utilisateur_id: 'user-directeur-snack',
    note_motif: 'Reconstitution du stock fournisseur Brasseries',
    sync_status: 'synced',
    client_timestamp: new Date(NOW - 3600 * 1000 * 24).toISOString(),
    created_at: new Date(NOW - 3600 * 1000 * 24).toISOString(),
  },
];

export const SEED_CLIENTS: Client[] = [
  {
    id: 'client-tchamba',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Papa TCHAMBA (Client VIP)',
    telephone_whatsapp: '237699112233',
    note_quartier: 'Résidence Akwa Nord',
    created_at: new Date(NOW - 3600 * 1000 * 24 * 10).toISOString(),
  },
  {
    id: 'client-mbele',
    etablissement_id: 'etab-capitole-douala',
    nom: 'Docteur MBELE',
    telephone_whatsapp: '237675998877',
    note_quartier: 'Cabinet Médical Akwa',
    created_at: new Date(NOW - 3600 * 1000 * 24 * 5).toISOString(),
  },
  {
    id: 'client-boutique-1',
    etablissement_id: 'etab-elegance-akwa',
    nom: 'Mme CHANTAL VIP',
    telephone_whatsapp: '237699445566',
    note_quartier: 'Bonapriso',
    created_at: new Date(NOW - 3600 * 1000 * 24 * 2).toISOString(),
  },
];

export const SEED_FACTURES: Facture[] = [
  {
    id: 'fac-1001',
    etablissement_id: 'etab-capitole-douala',
    numero_facture: 'FAC-2026-0041',
    utilisateur_id: 'user-caissiere-1',
    caissiere_id: 'user-caissiere-1',
    serveuse_id: 'user-serveuse-1',
    montant_total: 12000,
    montant_paye: 12000,
    montant_restant: 0,
    mode_paiement: 'cash',
    statut: 'payee',
    created_at: new Date(NOW - 3600 * 1000 * 5).toISOString(),
    lignes: [
      {
        id: 'lig-1',
        facture_id: 'fac-1001',
        produit_id: 'prod-guinness',
        nom_produit: 'Guinness Foreign Extra',
        quantite_bouteilles: 12,
        prix_unitaire_vente: 1000,
        cout_unitaire_cmp: 458,
        sous_total_vente: 12000,
        sous_total_cout: 5496,
        marge_brute: 6504,
      },
    ],
  },
];

export const SEED_REMBOURSEMENTS: RemboursementCredit[] = [];
export const SEED_CHARGES: ChargeJournaliere[] = [];
